//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoboRadio.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoboRadio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Avatar {
            get {
                object obj = ResourceManager.GetObject("Avatar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;filters&gt;
        ///	&lt;filter IsTwoFields=&quot;True&quot;&gt;
        ///		&lt;prefix&gt;is now playing on NonStopPlay UK&lt;/prefix&gt;
        ///		&lt;suffix&gt;
        ///		&lt;/suffix&gt;
        ///	&lt;/filter&gt;
        ///&lt;/filters&gt;.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [Volume]
        ///Value = 0
        ///[Saving]
        ///SaveStationOnExit = False
        ///SaveShazamStateOnExit = False
        ///SavedStationNumber = -1
        ///DisableShazam = False
        ///VisColor = 666.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;stations&gt;
        ///  &lt;station name=&quot;Awesome 80&apos;s&quot;&gt;
        ///    &lt;link&gt;http://113fm.cdnstream1.com/1719_128?cb=61816.mp3&lt;/link&gt;
        ///  &lt;/station&gt;
        ///  &lt;station name=&quot;Nirvana Ambient Radio&quot;&gt;
        ///    &lt;link&gt;http://radio.108.pl:8006/ambient.ogg&lt;/link&gt;
        ///  &lt;/station&gt;
        ///  &lt;station name=&quot;Tangra Mega Rock&quot;&gt;
        ///    &lt;link&gt;http://stream-bg-01.radiotangra.com:8000/Tangra.ogg&lt;/link&gt;
        ///  &lt;/station&gt;
        ///  &lt;station name=&quot;Punkrockers Radio&quot;&gt;
        ///    &lt;link&gt;http://stream.punkrockers-radio.de:8000/ogg&lt;/link&gt;
        ///  &lt;/station&gt;        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Stations {
            get {
                return ResourceManager.GetString("Stations", resourceCulture);
            }
        }
    }
}
